import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { getStudentHallTicket } from '../../api/axios';
import { Ticket, CheckCircle, XCircle, Download, AlertTriangle } from 'lucide-react';

export default function StudentHallTicket() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getStudentHallTicket(user.studentId).then(r => setData(r.data)).finally(() => setLoading(false));
  }, [user.studentId]);

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <div className="animate-pulse bg-white rounded-xl h-64" />;

  return (
    <div className="space-y-6 animate-fade-in" id="hall-ticket-container">
      <div className="flex justify-between items-center print:hidden">
        <h1 className="text-2xl font-bold text-[#1B263B] font-[DM_Sans]">Hall Ticket</h1>
        {data?.eligible && (
          <button onClick={handlePrint} className="px-4 py-2 bg-[#1B263B] text-white rounded-lg font-medium hover:bg-[#2d3e5c] flex items-center gap-2 transition-all shadow-sm">
            <Download size={18} /> Print / Download PDF
          </button>
        )}
      </div>

      <div className={`rounded-xl p-8 text-center ${data?.eligible ? 'bg-green-50 border-2 border-green-200' : 'bg-red-50 border-2 border-red-200'}`}>
        {data?.eligible ? (
          <>
            <CheckCircle size={48} className="mx-auto text-[#354F52] mb-4 print:hidden" />
            <h2 className="text-2xl font-bold text-[#354F52]">✅ Eligible for Examinations</h2>
            <p className="text-gray-600 mt-2">You meet the minimum attendance requirement of {data.minAttendance}%</p>
            <div className="hidden print:block mt-8 text-left border-t border-gray-300 pt-6">
              <h3 className="text-xl font-bold text-center mb-4 uppercase tracking-widest text-[#1B263B]">Admit Card - Spring 2026</h3>
              <p className="text-sm text-gray-500 text-center mb-6">This document is auto-generated by CampusIQ and authorizes the student to appear for the end-semester examinations.</p>
            </div>
          </>
        ) : (
          <>
            <XCircle size={48} className="mx-auto text-[#A4161A] mb-4" />
            <h2 className="text-2xl font-bold text-[#A4161A]">❌ Not Eligible</h2>
            <p className="text-gray-600 mt-2">You do not meet the minimum attendance requirement of {data?.minAttendance}%</p>
          </>
        )}
      </div>

      {data?.ineligibleSubjects?.length > 0 && (
        <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100 print:hidden">
          <h3 className="font-semibold text-[#1B263B] mb-4 flex items-center gap-2"><AlertTriangle size={18} className="text-[#A4161A]" />Insufficient Attendance</h3>
          <div className="space-y-3">
            {data.ineligibleSubjects.map((s, i) => (
              <div key={i} className="flex items-center justify-between p-3 bg-red-50 rounded-lg">
                <span className="text-sm font-medium text-red-800">{s.subject} ({s.code})</span>
                <span className="text-sm text-red-600 font-semibold">{s.attendance}%</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data?.student && (
        <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
          <h3 className="font-semibold text-[#1B263B] mb-4 border-b pb-2">Student Details</h3>
          <div className="grid grid-cols-2 gap-y-4 gap-x-8 text-sm">
            <div><span className="text-gray-500 block text-xs uppercase mb-1">Name</span> <span className="font-semibold text-lg">{data.student.name}</span></div>
            <div><span className="text-gray-500 block text-xs uppercase mb-1">Roll No</span> <span className="font-semibold text-lg">{data.student.roll_no}</span></div>
            <div><span className="text-gray-500 block text-xs uppercase mb-1">Semester</span> <span className="font-medium text-base">{data.student.semester}</span></div>
            <div><span className="text-gray-500 block text-xs uppercase mb-1">Section</span> <span className="font-medium text-base">{data.student.section}</span></div>
            <div className="col-span-2"><span className="text-gray-500 block text-xs uppercase mb-1">Department</span> <span className="font-medium text-base">{data.student.department}</span></div>
          </div>
          
          <div className="hidden print:block mt-12 pt-8 border-t border-gray-300">
             <div className="flex justify-between px-8">
               <div className="text-center">
                 <div className="w-48 border-b border-gray-400 mb-2"></div>
                 <span className="text-sm font-medium text-gray-600">Student Signature</span>
               </div>
               <div className="text-center">
                 <div className="w-48 border-b border-gray-400 mb-2"></div>
                 <span className="text-sm font-medium text-gray-600">Controller of Examinations</span>
               </div>
             </div>
          </div>
        </div>
      )}
    </div>
  );
}
